import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { Providers } from "../components";

import "./globals.css";
import { Info } from "@/enums";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: Info.TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} dark bg-black`}>
        <Toaster position="top-right" />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
