// Generated by https://quicktype.io

export interface User {
  _id:             string;
  full_name:       string;
  types:           string[];
  roles:           string[];
  email:           string;
  idCompany:       null;
  login_google:    boolean;
  img:             null;
  companyKumonera: null;
}
